### DISCUSSION TITLE
Aiguillage différé vers un formulaire, via un courriel de reprise - Données non modifiable?

### DISCUSSION THREAD

**Discussion by jpbeaulieu1** [MTESSDev/utd-webcomponents#71] [Q&A]
Bonjour

Nous utilisons la fonctionnalité d'aiguillage pour forcer les utilisateurs à valider leur adresses courriel.   Nous demandons quel formulaire ils veulent compléter et nous leur demandons le courriel et le mot de passe pour que l'aiguillage les envoie sur le bon formulaire. Ça  fonctionne bien. L'adresse courriel est aussi bien préremplie dans le formulaire 2 puis que le groupe et le champs porte le même nom. Par contre nous constatons est que peu importe les autres champs présents dans le groupe portant le même nom dans le formulaire 2, nous ne recevons que les données du formulaire 1. Nous nous attendions à recevoir toutes les données du formulaire 2. Est-ce que nous utilisons la fonctionnalité correctement?

J'ai ce groupe dans mon formulaire 1:
```
 - type: group
   name: informationDemandeur
   components:
   - name: courriel
     type: email
     label:
       fr: Courriel
       en: Email address
     help :
       fr: Un message de validation vous sera envoyé à cette adresse courriel. Veuillez verifier vos indésirables si vous n'avez rien reçu.
       en: (eng) Un message de validation vous sera envoyé à cette adresse courriel. Veuillez verifier vos indésirables si vous n'avez rien reçu.
   - name: courrielConfirmation
     type: email
     label:
       fr: Courriel (confirmation)
       en: Email address (confirmation)
     validations:
       confirm: courriel
   - type: password
            name: MDPAConfirmer
            label: 
                fr: Mot de passe
                en: (EN)Confirmer le mot de passe
          - type: password
```
Dans le formulaire 2, j'ai le même groupe mais avec d'autres champs en plus du courriel
```
- type: group
  name: informationDemandeur
  components:
  - name: salutation
    type: radio
    label:
      fr: Salutation
      en: (eng) Salutation
    options:
      Mr.:
        fr: Monsieur
        en: (eng) Monsieur
      Mrs.:
        fr: Madame
        en: (eng) Madame

  - name: nom
    type: text
    label:
      fr: Nom
      en: Name
  - name: prenom
    type: text
    label:
      fr: Prénom
      en: First name
  - name: dateNaissance
    type: date
    label:
      fr: Date de naissance
      en: Date of birth
    validations:
      before:
  - name: courriel
     type: email
     label:
       fr: Courriel
       en: Email address
     additionals:
       :disabled: true
```

Dans les outil de Dev en IT, je vois bien les données
```
"form": {
          {
            "salutation": "Mr.",
            "nom": "INC.",
            "prenom": "FERME",
            "telephone": "418 999-9999",
            "courriel": "test@rbq.gouv.qc.ca",
            "dateNaissance": "2024-05-28",
        }
}
```
Mais les données envoyé sont seulement celle du formulaire 1
```
"donneesFormulaire": {
      "form": {
        "informationDemandeur": [
          {
            "courriel": "test@rbq.gouv.qc.ca",
            "courrielConfirmation": "test@rbq.gouv.qc.ca",
          }
        ],
      },
      "systeme": {},
      "formProtege": {
        "validAll": true,
        "EtatRevision": "sans-erreur",
        "PjManquantes": [],
        "informationDemandeur": [
          {
            "courriel": "test@rbq.gouv.qc.ca",
            "courrielConfirmation": "test@rbq.gouv.qc.ca",
          }
        ],
        "courrielDestination": "jean-pierre.beaulieu-ext@rbq.gouv.qc.ca",
        "MDPConfirmation": "Test4"
      },
      "config": {
        "domaines": {}
      },
      "X-NoConfirmation": 9999999999311,
      "X-DateTransmission": "2024-06-20T13:26:03.3722948-04:00"
```

Normalement, je devrais recevoir les données complètes du 2e formulaires
